server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # proxy_pass http://devops-tiga-be-service:8080;
        proxy_pass http://devops-tiga-be-service:8080/;
    }

    location = /favicon.ico {
    access_log off;
    log_not_found off;
    return 204;
    }

}
